### ISSUE TITLE
micro_speech example

### ISSUE THREAD

**Issue by kevin789654tw** [HimaxWiseEyePlus/himax_tflm#19]
Dear @kris-himax 

Hi. I've been working on micro_speech example lately.
I'd like to know which algorithm you use (yolo fastest or something else). It will help me a lot. Thank you.

Best Regards,
Kevin

**Comment by kris-himax** [comment]
@kevin789654tw , hi

This is the google tflite-micro example.
You can see more detail about the algorithm at (https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples/micro_speech/train#trained-models).

Thanks,
Kris

**Comment by kevin789654tw** [comment]
Dear @kris-himax

Thank you. I'll study on it.

Thanks,
Kevin
