### ISSUE TITLE
Visualizing the images from himax camera.

### ISSUE THREAD

**Issue by PCPJ** [HimaxWiseEyePlus/himax_tflm#20]
Hello everyone.
I would like to know if there is a good and easy way to retrieve the images being captured from the camera.
I would like to see the captured image, and the model output from that image.
There is a way to send the image thought USB for example?
I think it is a silly question, but I don't have much experience with this kind of hardware. Any help is welcome.
Thank you so much.

**Comment by kris-himax** [comment]
@PCPJ hi,
You can reference LAB1_capture_image example under the below repository. https://github.com/HimaxWiseEyePlus/bsp_tflu/tree/master/HIMAX_WE1_EVB_example/scenario_app/workshop_example

see the captured image: 
- Step1: The easy way is to use our  `PC_TOOL_Linux`, you can download [here](https://github.com/HimaxWiseEyePlus/WE_I_Plus_User_Examples/releases/download/v1.0/PC_TOOL_Linux).
- Step2: please key-in following command on console.
 ```
chmod 777 PC_TOOL_Linux
```
- Step3: Install FT4222 linux driver: 
You can reference the user guide [here](https://github.com/HimaxWiseEyePlus/bsp_tflu/tree/master/HIMAX_WE1_EVB_user_guide#update-bootloader-version-at-linux-environment) to download and install FT4222 linux driver.
- Step4: 
![Screenshot from 2022-12-02 16-40-03](https://user-images.githubusercontent.com/87454575/205252276-97ea9723-6b62-48dd-938e-9fa5e36429a9.png)
Then you will see the captured images on the PC and just need to connect by the USB cable.
The more detailed introduction about this tool you can reference the below example.
https://github.com/HimaxWiseEyePlus/WE_I_Plus_User_Examples/tree/main/HIMAX_Yolo_Fastest_Person_Detection_Example

If you want to see the model output, you can reference the SPI TOOL code (https://github.com/HimaxWiseEyePlus/bsp_tflu/tree/master/SPI_Tool#spi-tool-for-receive-meta-data-and-images-from-himax_we1_evb) and change it to receive meta data which you define yourself for your own model output.

**Comment by chinya07** [comment]
Thanks for the help @kris-himax regarding the visualization using SPI Tool. However for some reason I am not able to see anything on the `image window` when I connected my Himax WE-I Plus via USB. I am sharing the screenshots of my console output and the SPI Tool UI. Do you have any idea what might be the issue?
<img width="730" alt="Screenshot 2023-01-05 at 11 54 52 AM" src="https://user-images.githubusercontent.com/38719024/210775793-aea0dfd0-63c1-4476-a3d7-b1a871556daf.png">
<img width="1181" alt="Screenshot 2023-01-05 at 11 55 59 AM" src="https://user-images.githubusercontent.com/38719024/210775813-1f8df7f2-6a11-4b92-a213-41fb26f56156.png">
