### ISSUE TITLE
有關SDK之API需求

### ISSUE THREAD

**Issue by U3807** [HimaxWiseEyePlus/himax_tflm#4]
Himax 您好

請問有關WE-I 開發板，是否有相關的Timer API可以使用？
因為我們看完完整的header file後，好像沒有找到相關API。

謝謝您!!!

**Comment by bigcat-himax** [comment]
Hi, 
可以參照 hx_drv_tflm.h
hx_drv_tick_get API, WE-I 跑在 400Mhz, 表示兩次hx_drv_tick_get API取得的 tick 數值差如果為 400M, 則表示這兩次hx_drv_tick_get 之間過了 1秒
