### ISSUE TITLE
`atof()` fails/hangs system if character string length is 17 or more using GNU Toolchain

### ISSUE THREAD

**Issue by rajames** [HimaxWiseEyePlus/himax_tflm#9]
Ways to reproduce:
- Add `float value = atof("9.612345678912345");` in e.g. person_detection/main_functions.cc.
- build with ARC GNU Toolchain and flash.

Result:
System hangs and is unresponsive.

**Comment by bigcat-himax** [comment]
@rajames We test gnu toolchain with version 
- "arc_gnu_2020.09_prebuilt_elf32_le_linux_install"
- "arc_gnu_2020.03_prebuilt_elf32_le_linux_install"
, same result here.
Document about atof function library "arc_gnu_2020.09_prebuilt_elf32_le_linux_install/share/doc/newlib/libc.pdf"
section 2.7 atof, atoff—string to double or float
it does not mention about length limitation to use for atof function

Test with MW toolchain and works fine, we suggest avoid to use this testcase while build with gnu toolchain
